// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ascooiwvfplmkmlrtcnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzY29vaXd2ZnBsbWttbHJ0Y25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODAwOTcsImV4cCI6MjA3MzQ1NjA5N30.37obDXHuHZlALbrDOWsVVrSuP5Smsz1GLrGFYejYVD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});